[[lib-html-exporter]]
lib-html-exporter
-----------------

An Enonic XP’ified JAVA library to Export CSS styled HTML to various
Formats (XLSX, ODS, PDF, DOCX etc)

Word and OO Writer both open HTML documents regardless of the file
extension so whether this is worth looking at remains to be seen.

The library is a wrapper around html-exporter it’s an old project but
works and has great use cases.

[[usage]]
Usage
~~~~~

To install this library you need to update your build.gradle file.

[[gradle-build-script]]
Gradle build script
^^^^^^^^^^^^^^^^^^^

[[enonic-xp-version-6.12]]
Enonic XP version >=6.12
++++++++++++++++++++++++

....
dependencies {
    include 'openxp.lib:htmlexporter:0.1.0'
}
....

[[enonic-xp-version-6.11]]
Enonic XP version <=6.11
++++++++++++++++++++++++

....
repositories {
    maven {
      url 'https://dl.bintray.com/openxp/enonic'
    }
}

dependencies {
     include 'openxp.lib:htmlexporter:0.1.0'
}
....

[[documentation]]
Documentation
-----


Example usage:

....
var htmlExporter = require('/lib/openxp/html-exporter');
var ioLib = require("/lib/xp/io");

exports.get = function(req, type) {
    var fileSource = null;
    var fileName = "htmlExporterTest";

    if(type == "pdf"){
        fileSource = htmlExporter.exportToPdf( getHtml() );
        fileName += ".pdf";
    }else{
        fileSource = htmlExporter.exportToExcel( getHtml() );
        fileName += ".xlsx";
    }

    fileSource.name = fileName;

    // Stream the file content to the client
    return {
            body:  htmlExporter.getStream(fileSource),
            headers : {
            "Content-Disposition": 'attachment; filename="' + fileSource.name + '"'
            }
    };

};

function getHtml(){
    return ioLib.readText(ioLib.getResource(resolve('html-exporter-test.html')).getStream());
}
....

The reports linked to above were generated via a demo application which
is included in the source. This generates some data used to populate a
Velocity template. The resulting HTML is then exported to Excel, PDF and
Open Office Calc.

[[features]]
Features
--------

* Supports a limited subset of CSS: enough for producing nicely
formatted reports.
* Spreadsheet cell comments.
* Cells can span multiple rows and columns.
* Multiple sheets.
* Automatic formula insertion:
* Freeze panes

The ODS and Excel exporters allow for producing spreadsheets with
automatic formula insertion via the use of various HTML5 compliant
data-* attributes being applied to table cells. The sample spreadsheets
linked to above demonstrate this functionality.

Example:

....
<!-- This cell will, via the data-group attribute,  be added to two ranges, each of which will be the inputs to formulas -->
<td data-group="store_Dumfries_2_value, region_1_1_pg_5_value" class="numeric">
    486
</td>

...

<!--
    This raw value of this cell will, via the data-group-output attribute, be replaced with a SUM function taking as input all cells added to the specified range.
    The cell is then itself added to another range which will be used by a further function.
-->
<td class="subTotal numeric" data-group-output="region_1_1_pg_6_count" data-group="area_1_pg_6_cou
....